services:
  - type: web
    name: my-django-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgres://myuser:mypassword@db:5432/mydatabase
      - key: SECRET_KEY
        value: your_secret_key
