databases:
  - name: petprojectdb
    plan: free
    databaseName: pet_project_db
    user: pet_project_user

services:
  - type: web
    plan: free
    name: pet_project
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Pet_project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petprojectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
